#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void* getNextField(void* packet, size_t fieldSize, size_t packetSize)
{
    static size_t sum = 0;
    void* nextLocation = calloc(1, fieldSize);
    memcpy(nextLocation, packet + sum, fieldSize);
    sum += fieldSize;
    if (sum >= packetSize) {
        sum = 0;
    }
    return nextLocation;
}

int main()
{
//Messy - would usually be generated by a function. 
size_t packetSize = sizeof(uint8_t) + sizeof(uint16_t);
uint8_t packet[sizeof(uint8_t) + sizeof(uint16_t)] = {0};
packet[0] = 55;
*(uint16_t*)(packet+sizeof(uint8_t)) = 30000;

//Imaginary sending

//Read off values
uint8_t* firstValue = getNextField(packet, sizeof(uint8_t), packetSize);
uint16_t* secondValue = getNextField(packet, sizeof(uint16_t), packetSize); //Have read packetSize bytes, function should now be reset
printf("%u %u\n", *firstValue, *secondValue);
free(firstValue);
free(secondValue);

//Do it again to test reseting
firstValue = getNextField(packet, sizeof(uint8_t), packetSize);
secondValue = getNextField(packet, sizeof(uint16_t), packetSize);
printf("%u %u\n", *firstValue, *secondValue);
free(firstValue);
free(secondValue);
}